package com.example.feeasy.entities;

public enum ActionNames {
    SIGN_UP, SIGN_IN, CREATE_FEE, SAVE_PRESET, SET_FEE_STATUS, CREATE_GROUP, ADD_TO_GROUP, ALL_GROUPS, ALL_MEMBERS, ALL_FEES_OF_GROUP, ALL_PRESETS_OF_GROUP, FEES_OF_USER_IN_GROUP
}
